name: "Fetch Service Config"
description: "Action to fetch Service Config from Config Service"
author: "Anant Sharma"
inputs:
  access_token:
    description: "Github Access Token"
    required: true
  deploy:
    description: "Should Deploy"
    required: false
    default: "0"
outputs:
  DOCKER_USER:
    description: "Part of Config"
  DOCKER_PASS:
    description: "Part of Config"
  DOCKER_IMAGE_NAME:
    description: "Part of Config"
  TAG:
    description: "Part of Config"
  CLUSTER_API_URL:
    description: "Part of Config"
  CLUSTER_AUTH_TOKEN:
    description: "Part of Config"
  CLUSTER_CONTAINER_NAME:
    description: "Part of Config"
  HOST_PORT:
    description: "Part of Config"
  SLACK_WEBHOOK:
    description: "Part of Config"
runs:
  using: "node12"
  main: "dist/index.js"
